data:
    dataset: "dehaze"
    category: ""
    path: "/root/archive/train/"
    image_size: 512
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 8
    batch_size: 1
    out_of_dist: false

model:
    type: "openai"
    grayscale: False
    in_channels: 3
    out_channels: 3
    num_channels: 64
    num_heads: 4
    num_res_blocks: 1
    attention_resolutions: "16"
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: False
    use_scale_shift_norm: True
    use_fp16: False
    resblock_updown: True
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 512
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000
